---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: making/dcind-jdk
inputs:
  - name: repo
  - name: utils
  - name: m2
  - name: redis
run:
  path: sh
  args:
  - -c
  - |
    repo/ci/tasks/unit-test-with-redis.sh
params:
  _JAVA_OPTIONS: -Duser.timezone=Asia/Tokyo -Duser.language=ja -Duser.country=JP -Djava.security.egd=file:/dev/./urandom -Dos.name=win